unstable_features = true
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Mixed"
wrap_comments = true
fn_single_line = true
format_strings = true
use_field_init_shorthand = true
struct_lit_single_line = true
max_width = 100
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
